project:
  type: website

website:
  title: "simple_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: projects.qmd
        text: Projects
      - href: about.qmd
        text: About

editor: visual

